### ISSUE TITLE
windows端报错

### ISSUE THREAD

**Issue by 502milk** [MeowCat-Studio/discord-mesaga-fonto#1]
`INFO  discord_mesaga_fonto::message > Connecting to nats server
 INFO  discord_mesaga_fonto::message > Connected sucessfully
 ERROR serenity::gateway::shard      > [Shard [0, 1]] Disallowed gateway intents have been provided.
 ERROR serenity::client::bridge::gateway::shard_runner > Shard handler received err: Gateway(DisallowedGatewayIntents)
 WARN  serenity::client::bridge::gateway::shard_queuer > Failed to cleanly shutdown shard 0 when sending message to shard runner: TrySendError { kind: Disconnected }

`
出现后直接自动退出

**Comment by Itsusinn** [comment]
@502milk

**Comment by 502milk** [comment]
> @502milk ![wFq57.png](https://user-images.githubusercontent.com/30529002/128589888-d5ff98a2-b6d7-41f1-977c-77627c9aca35.png)

解决了 谢谢
